//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shimakaze.ToolKit.CSF.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shimakaze.ToolKit.CSF.GUI.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2019 - 2020 的本地化字符串。
        /// </summary>
        public static string UI_Copyright_p1 {
            get {
                return ResourceManager.GetString("UI_Copyright_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舰队的偶像-岛风酱! 的本地化字符串。
        /// </summary>
        public static string UI_Copyright_p2 {
            get {
                return ResourceManager.GetString("UI_Copyright_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string UI_ExitApplication {
            get {
                return ResourceManager.GetString("UI_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string UI_Import {
            get {
                return ResourceManager.GetString("UI_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string UI_NewFile {
            get {
                return ResourceManager.GetString("UI_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string UI_OpenFile {
            get {
                return ResourceManager.GetString("UI_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSF编辑器 改三 的本地化字符串。
        /// </summary>
        public static string UI_SplashWindow_Title {
            get {
                return ResourceManager.GetString("UI_SplashWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续但不打开文件  → 的本地化字符串。
        /// </summary>
        public static string UI_StartScreen_Continue {
            get {
                return ResourceManager.GetString("UI_StartScreen_Continue", resourceCulture);
            }
        }
    }
}
