//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RA2CsfEditor.Strings.en {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RA2CsfEditor.Strings.en.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Append... 的本地化字符串。
        /// </summary>
        public static string MenuItem_Append {
            get {
                return ResourceManager.GetString("MenuItem_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close the file 的本地化字符串。
        /// </summary>
        public static string MenuItem_CloseFile {
            get {
                return ResourceManager.GetString("MenuItem_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string MenuItem_Export {
            get {
                return ResourceManager.GetString("MenuItem_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Json... 的本地化字符串。
        /// </summary>
        public static string MenuItem_ExportToJson {
            get {
                return ResourceManager.GetString("MenuItem_ExportToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Text... 的本地化字符串。
        /// </summary>
        public static string MenuItem_ExportToTxt {
            get {
                return ResourceManager.GetString("MenuItem_ExportToTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Xml... 的本地化字符串。
        /// </summary>
        public static string MenuItem_ExportToXml {
            get {
                return ResourceManager.GetString("MenuItem_ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string MenuItem_Import {
            get {
                return ResourceManager.GetString("MenuItem_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import From Json... 的本地化字符串。
        /// </summary>
        public static string MenuItem_ImportFromJson {
            get {
                return ResourceManager.GetString("MenuItem_ImportFromJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import From Xml... 的本地化字符串。
        /// </summary>
        public static string MenuItem_ImportFromXml {
            get {
                return ResourceManager.GetString("MenuItem_ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open... 的本地化字符串。
        /// </summary>
        public static string MenuItem_Open_Text {
            get {
                return ResourceManager.GetString("MenuItem_Open.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string MenuItem_Save {
            get {
                return ResourceManager.GetString("MenuItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAs... 的本地化字符串。
        /// </summary>
        public static string MenuItem_SaveAs {
            get {
                return ResourceManager.GetString("MenuItem_SaveAs", resourceCulture);
            }
        }
    }
}
